"""Update Asset

Revision ID: 106b867e7587
Revises: edd199c6b2dc
Create Date: 2025-08-23 17:54:42.860909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106b867e7587'
down_revision = 'edd199c6b2dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('path')

    # ### end Alembic commands ###
