"""Update Asset

Revision ID: 2c9c91971620
Revises: 106b867e7587
Create Date: 2025-08-23 20:09:58.212387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c9c91971620'
down_revision = '106b867e7587'
branch_labels = None
depends_on = None

asset_status = sa.Enum("pending", "uploaded", "processing", "ready", "failed", name="asset_status")

def upgrade():
    asset_status.create(op.get_bind()) 
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status',asset_status , nullable=False, server_default="pending"))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('active')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
