"""Update users db

Revision ID: 32342f8d73c8
Revises: eb950b87b5de
Create Date: 2025-08-23 14:27:50.599439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32342f8d73c8'
down_revision = 'eb950b87b5de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    # ### end Alembic commands ###
