"""Add Event

Revision ID: 51023c27fd56
Revises: a9b7d6ddc650
Create Date: 2025-08-23 16:53:13.506167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51023c27fd56'
down_revision = 'a9b7d6ddc650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
