"""Add live status to event

Revision ID: 5fb38d133240
Revises: fe8e5c53bf20
Create Date: 2025-08-25 01:03:47.167679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb38d133240'
down_revision = 'fe8e5c53bf20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('live',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('live',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
