"""Update Asset add status and active

Revision ID: a51d34e4cd1e
Revises: 2c9c91971620
Create Date: 2025-08-23 20:33:24.738614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a51d34e4cd1e'
down_revision = '2c9c91971620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('assets_mime_type_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('assets_mime_type_key'), ['mime_type'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
