"""Add live status to event

Revision ID: fe8e5c53bf20
Revises: a51d34e4cd1e
Create Date: 2025-08-25 01:02:44.542050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe8e5c53bf20'
down_revision = 'a51d34e4cd1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('live', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('live')

    # ### end Alembic commands ###
